name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # ⚡ Important: use self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 10.1.67.158 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          scp -r ./dist nucleus@10.1.67.158:/home/nucleus/app
          ssh nucleus@10.1.67.158 "cd /home/nucleus/app && docker compose up -d --build"
